name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run full test suite
        run: |
          echo "🧪 Running full test suite for release..."
          bun run typecheck
          bunx playwright install chromium
          bun run test

      - name: Verify package integrity
        run: |
          echo "📦 Verifying package integrity..."
          bun run format --check

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            ## Changes in ${{ steps.get_version.outputs.VERSION }}

            ### Features
            - See commit history for detailed changes

            ### Bug Fixes
            - See commit history for detailed changes

            ### Installation
            ```bash
            # From npm (recommended)
            npx web-developer-mcp

            # From source
            git clone https://github.com/${{ github.repository }}.git
            cd web-developer-mcp
            bun install
            bun start
            ```

            ### Requirements
            - Node.js 18+ or Bun runtime
            - AI assistant with MCP support (Claude Code, Cursor, etc.)
          draft: false
          prerelease: false
